
services:
  # Сервис базы данных PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: erp_postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" # <-- ВОТ ТАК
      timeout: 5s
      retries: 5

  # Бэкенд на Express
  backend:
    build:
      context: ./backend
    container_name: erp_backend
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    
    restart: unless-stopped
    command: >
      sh -c "echo 'Waiting 5s for DB to be truly ready...' && sleep 5 && npx prisma migrate deploy && npx prisma db seed && npm run start" 
    depends_on:
      postgres:
        condition: service_healthy
  # Фронтенд на React
  frontend:
    build:
      context: ./frontend
    container_name: erp_frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
